//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AircraftControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAircraft
    {
        public int ID_AIRCRAFT { get; set; }
        public string PREFIX { get; set; }
        public decimal MAX_DEPARTURE_WEIGHT { get; set; }
        public decimal MAX_LANDING_WEIGHT { get; set; }
        public Nullable<int> PASSENGERS_COUNT { get; set; }
        public Nullable<decimal> WINGSPAN { get; set; }
        public bool ACTIVE { get; set; }
        public int ID_AIRCRAFTMODEL { get; set; }
    
        public virtual tblAircraftModel tblAircraftModel { get; set; }
    }
}
